"""Exact responsive catalogue identities; discovery is not execution proof."""
# Canonical 177-row catalogue SHA256: de688c77d7ac3b725023cac6b8ecef2daa220aa04e1aa57312591f95710c9cf3
CASES = (
    ('focus-audit.spec.ts', 'populated Player pages expose visible keyboard highlights at 390px'),
    ('focus-audit.spec.ts', 'populated Player pages expose visible keyboard highlights at 1440px'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 1440px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 1024px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 900px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 720px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 390px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta library more pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta utilities pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta settings pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta system settings pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta connection settings pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta onboarding pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta media pages fit the 320px viewport'),
    ('layout-audit-beta.spec.ts', 'beta created pages fit the 320px viewport'),
    ('layout-audit-configuration.spec.ts', 'SCIM configuration stays usable at every supported width'),
    ('layout-audit-configuration.spec.ts', 'single sign-on configuration stays usable at every supported width'),
    ('layout-audit-configuration.spec.ts', 'SAML configuration stays usable at every supported width'),
    ('layout-audit-configuration.spec.ts', 'software update choices stay clear at supported widths'),
    ('layout-audit-configuration.spec.ts', 'Media Shares keeps its heading and controls in a readable composition'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 1440px'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 1024px'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 900px'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 768px'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 390px'),
    ('layout-audit-configuration.spec.ts', 'Owner settings separates everyday preferences from advanced tools at 320px'),
    ('layout-audit-library.spec.ts', 'browse shows artwork before scrolling on desktop and phone'),
    ('layout-audit-library.spec.ts', 'ordinary browse keeps results in the first useful viewport'),
    ('layout-audit-library.spec.ts', 'mobile browse spacing holds across every media page'),
    ('layout-audit-library.spec.ts', 'compact landscape shell keeps search and primary actions reachable'),
    ('layout-audit-navigation.spec.ts', 'Owner actions remain reachable on desktop and phone'),
    ('layout-audit-navigation.spec.ts', 'French global search remains readable and usable on narrow phones'),
    ('layout-audit-navigation.spec.ts', 'empty My List gives a keyboard recovery path'),
    ('layout-audit-navigation.spec.ts', 'functional motion stays restrained and respects reduced motion'),
    ('layout-audit-navigation.spec.ts', 'library language picker stays clear of compact fixed controls'),
    ('layout-audit-navigation.spec.ts', 'Viewer navigation exposes connection and account actions without Owner tools'),
    ('layout-audit-navigation.spec.ts', 'desktop library navigation remains reachable in its own scroll region'),
    ('layout-audit-navigation.spec.ts', 'continue watching actions share a baseline when titles wrap'),
    ('layout-audit-player.spec.ts', 'player shows and switches its playback method without crowding actions'),
    ('layout-audit-player.spec.ts', 'player stays accessible in alternate display modes'),
    ('layout-audit-player-recovery.spec.ts', 'player explains an unconfirmed failure and offers a direct retry'),
    ('layout-audit-player.spec.ts', 'artwork-backed media copy remains readable'),
    ('layout-audit-shell.spec.ts', 'signed-in application pages retain the navigation shell'),
    ('layout-audit-shell.spec.ts', 'transcoder support stays concise and accessible'),
    ('layout-audit-workflows.spec.ts', 'representative workflows hold in dark theme with reduced motion'),
    ('loading-review.spec.ts', 'player stage stays visible across loading and bandwidth changes'),
    ('masthead-spacing.spec.ts', 'Home keeps continued titles and navigation reachable'),
    ('masthead-spacing.spec.ts', 'Home resume remains accessible across appearance and input preferences'),
    ('masthead-spacing.spec.ts', 'Show seasons stay below the desktop header while scrolling'),
    ('watch-backdrop-contrast.spec.ts', 'watch-page hints stay readable over extreme artwork'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 1440px'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 1024px'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 900px'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 720px'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 390px @smoke'),
    ('setup-and-skip-navigation.spec.ts', 'TMDB instructions stay readable at 320px'),
    ('setup-and-skip-navigation.spec.ts', 'show skip link moves keyboard focus to the main content at 1440px @smoke'),
    ('setup-and-skip-navigation.spec.ts', 'show skip link moves keyboard focus to the main content at 390px @smoke'),
)
