#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Helpers below support only the remote-access stages in this script.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
SKIPPED=()        # steps left for the user

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
ENV_FILE="$root/.env"

banner "Secure Kinosail remote access"

stage "Choose the private boundary"
[[ -f "$ENV_FILE" ]] || { warn "Install Kinosail and create the Owner Profile first."; exit 1; }
say "Use HTTPS for ordinary viewing apps. The legacy WireGuard mode pairs Viewer devices. For Owner access while away, use Settings → Manage while away."
ask KINOSAIL_REMOTE_MODE "Mode (https or wireguard) [https]:"
KINOSAIL_REMOTE_MODE="${KINOSAIL_REMOTE_MODE:-https}"
[[ "$KINOSAIL_REMOTE_MODE" == "off" ]] && KINOSAIL_REMOTE_MODE=https
case "$KINOSAIL_REMOTE_MODE" in
  wireguard|https) ;;
  *) warn "Mode must be wireguard or https."; exit 2 ;;
esac
if command -v podman >/dev/null && podman compose version >/dev/null 2>&1; then
  compose=(podman compose)
elif command -v docker >/dev/null && docker compose version >/dev/null 2>&1; then
  compose=(docker compose)
else
  warn "Install Podman Compose or Docker Compose first."; exit 1
fi
if [[ "$KINOSAIL_REMOTE_MODE" == "https" ]]; then
  say "Public HTTPS is for watching away from home. Owner settings stay on your home network or a separately paired private management device."
  step "Before continuing, create a remote-enabled Viewer in Settings and limit it to the Libraries they need."
  step "Sign in locally as that Viewer, open Account, and set up an authenticator app. Keep this device signed in for Quick Connect approval."
  note "For playback only, leave Allow downloads off. Public password-only sign-in and public passkey registration are blocked."
  pause "Press Enter when the Viewer is ready"
else
  note "WireGuard exposes no public Kinosail HTTPS listener."
fi

stage "Create the DuckDNS name"
open_url "https://www.duckdns.org/"
step "Sign in, create one subdomain, and copy only the label before .duckdns.org."
ask KINOSAIL_DUCKDNS_DOMAIN "DuckDNS subdomain label:"
if [[ ! "$KINOSAIL_DUCKDNS_DOMAIN" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
  warn "Use one lowercase DNS label containing only letters, numbers, and internal hyphens."
  exit 2
fi
if [[ -s "$root/secrets/duckdns_token" ]] && confirm "Reuse the existing hidden DuckDNS token?"; then
  KINOSAIL_DUCKDNS_TOKEN="$(<"$root/secrets/duckdns_token")"
else
  step "Copy the token shown by DuckDNS. It will be stored only in a mode-0600 secret file."
  ask_secret KINOSAIL_DUCKDNS_TOKEN "DuckDNS token:"
fi
if [[ ! "$KINOSAIL_DUCKDNS_TOKEN" =~ ^[A-Za-z0-9_-]{32,128}$ ]]; then
  warn "The DuckDNS token must contain 32–128 safe characters."
  exit 2
fi
umask 077
mkdir -p "$root/secrets"
printf '%s' "$KINOSAIL_DUCKDNS_TOKEN" >"$root/secrets/duckdns_token"
chmod 600 "$root/secrets/duckdns_token"
unset KINOSAIL_DUCKDNS_TOKEN
write_env KINOSAIL_DUCKDNS_DOMAIN "$KINOSAIL_DUCKDNS_DOMAIN"
write_env KINOSAIL_DUCKDNS_TOKEN_FILE /run/secrets/kinosail_duckdns_token
write_env KINOSAIL_DUCKDNS_TOKEN_PATH ./secrets/duckdns_token

stage "Enable Kinosail"
previous_mode="$(_existing KINOSAIL_REMOTE_MODE || true)"
write_env KINOSAIL_REMOTE_MODE "$KINOSAIL_REMOTE_MODE"
if [[ "$KINOSAIL_REMOTE_MODE" == "https" ]]; then
  # Save the original even when empty; reruns must not replace it with the public origin.
  if ! _existing KINOSAIL_LOCAL_AUTH_URL >/dev/null; then
    local_auth="$(_existing KINOSAIL_AUTH_URL || true)"
    [[ "$previous_mode" != "https" ]] || local_auth=""
    write_env KINOSAIL_LOCAL_AUTH_URL "$local_auth"
  fi
  write_env KINOSAIL_AUTH_URL "https://$KINOSAIL_DUCKDNS_DOMAIN.duckdns.org"
  write_env KINOSAIL_REMOTE_LISTEN :8443
  say "Restart Kinosail with its secure HTTPS override:"
  step "Run ./scripts/install.sh using the same media path and port as the current installation."
else
  if _existing KINOSAIL_LOCAL_AUTH_URL >/dev/null; then
    write_env KINOSAIL_AUTH_URL "$(_existing KINOSAIL_LOCAL_AUTH_URL)"
  fi
	  if command -v sudo >/dev/null 2>&1; then
	    sudo install -d -o 10001 -g 10001 -m 700 "$root/wireguard"
	  else
	    warn "sudo is required once to create the private WireGuard state directory for Kinosail's unprivileged user."
	    exit 1
	  fi
	  write_env KINOSAIL_WIREGUARD_PATH ./wireguard
	  write_env KINOSAIL_WIREGUARD_DIR /wireguard
	  say "Restart Kinosail with its WireGuard override, then create Viewer device profiles in Settings → Watch away from home."
	  step "After creating the first Viewer profile, run: sudo install -m 600 '$root/wireguard/wg_confs/kinosail.conf' /etc/wireguard/kinosail.conf"
	  step "Enable the private interface: sudo systemctl enable --now wg-quick@kinosail"
	  note "After adding or revoking another Viewer, run sudo ./scripts/sync-wireguard.sh to apply the new peer list without restarting Kinosail."
fi

image="$(_existing KINOSAIL_IMAGE || true)"
compose_file=compose.yaml
[[ "$image" =~ ^ghcr\.io/mikeo7/kinosail-player@sha256:[a-f0-9]{64}$ ]] && compose_file=compose.release.yaml
if [[ "$compose_file" == compose.yaml ]]; then
  export KINOSAIL_IMAGE=localhost/kinosail:dev
  write_env KINOSAIL_IMAGE "$KINOSAIL_IMAGE"
fi
if confirm "Restart Kinosail and apply this configuration now?"; then
  project=("${compose[@]}" --file "$compose_file")
  [[ ! -f kinosail.yaml ]] || project+=(--file compose.config.yaml)
  project+=(--file "compose.remote-$KINOSAIL_REMOTE_MODE.yaml")
  if [[ "$compose_file" == compose.yaml ]]; then "${project[@]}" build kinosail; fi
  "${project[@]}" up --detach --force-recreate --remove-orphans
  ready=""
  for _ in {1..40}; do
    if "${project[@]}" exec -T kinosail kinosail healthcheck >/dev/null 2>&1; then ready=yes; break; fi
    sleep 0.5
  done
  [[ -n "$ready" ]] || { "${project[@]}" logs --tail 50 kinosail >&2; warn "Kinosail did not become healthy."; exit 1; }
  say "Kinosail restarted with secure remote access."
else
  SKIPPED+=("Restart Kinosail to apply secure remote access")
fi

stage "Open only the selected path"
if [[ "$KINOSAIL_REMOTE_MODE" == "https" ]]; then
  step "Reserve this Server's LAN IP in your router's connected-device list (DHCP reservation)."
  step "In the router app or settings, find Port forwarding (also called Virtual server or NAT forwarding)."
  say "Name / service:          Kinosail HTTPS"
  say "Device / internal IP:    The Server computer's reserved LAN address"
  say "Protocol:                TCP only"
  say "External / public port:  443"
  say "Internal / private port: 443"
  note "For start and end ports, enter 443 in both. Save this single rule."
  step "Allow inbound TCP 443 in the Server firewall. The container maps host 443 to container 8443; do not forward to host 8443."
  note "Do not expose TCP 80 or the LAN port, disable the firewall, or use a router DMZ."
  note "If your router has a private WAN address or carrier-grade NAT, ask your provider for a public address or use an owner-controlled VPN compatible with your network. Two routers may need forwarding on both."
  step "Open Settings → Watch away from home → Set up access away from home for official router guides, troubleshooting, and Server checks."
  step "Turn Wi-Fi off on your phone. Open https://$KINOSAIL_DUCKDNS_DOMAIN.duckdns.org in a browser and choose Get a sign-in code."
  note "In Kinosail or a compatible Jellyfin app, add that address and choose Quick Connect."
  step "On the home device, approve the matching code as your remote-enabled Viewer. Play a movie and try seeking."
  note "Never approve an unexpected code or bypass a certificate warning at the public address."
  note "The first certificate can take a short time. Settings shows starting, ready, error, or killed without revealing the token."
else
  step "Forward router UDP 51820 to the WireGuard host. Do not expose Kinosail's HTTPS port."
  step "Import the downloaded Viewer profile into the WireGuard app, connect, then open the Kinosail address in that profile."
fi
say "Emergency stop: use Settings → Watch away from home, or run ./scripts/disable-remote-access.sh on the host."

SKIPPED+=("Confirm outside access from cellular data; local health does not prove router ports are reachable")
finish
