#!/usr/bin/env python3
"""Exercise the file-cap command and Git hooks against isolated repositories."""

from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
CHECKER = 'scripts/tooling/check-file-loc.py'
LEGACY = 'apps/player/apps/native/Sources/Platform/PlaybackCoordinator.swift'


class FileCapTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.repo = Path(self.temp.name)
        self.git('init', '-q')
        self.git('config', 'user.email', 'tests@example.invalid')
        self.git('config', 'user.name', 'File cap test')
        (self.repo / 'scripts/tooling').mkdir(parents=True)
        shutil.copy2(ROOT / CHECKER, self.repo / CHECKER)
        (self.repo / '.gates-disabled').touch()

    def git(self, *args):
        return subprocess.check_output(['git', '-C', str(self.repo), *args])

    def write(self, name, count, trailing=True):
        path = self.repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('\n'.join(['line'] * count) + ('\n' if trailing else ''))
        return path

    def run_cap(self, *args, expected=0):
        before = self.git('status', '--porcelain', '-z')
        result = subprocess.run(['python3', str(self.repo / CHECKER), *args],
                                capture_output=True, text=True)
        self.assertEqual(result.returncode, expected, result.stdout + result.stderr)
        self.assertEqual(self.git('status', '--porcelain', '-z'), before)
        return result

    def test_exact_boundary_for_each_language(self):
        for suffix in ('go', 'swift', 'ts', 'tsx', 'js', 'mjs', 'py', 'sh', 'css', 'html'):
            for trailing in (True, False):
                with self.subTest(suffix=suffix, trailing=trailing):
                    name = f'apps/player/example.{suffix}'
                    self.write(name, 300, trailing)
                    self.run_cap()
                    self.write(name, 301, trailing)
                    self.assertIn(name, self.run_cap(expected=1).stderr)
                    (self.repo / name).unlink()

    def test_legacy_files_cannot_grow_and_strict_lists_debt(self):
        self.write(LEGACY, 616)
        self.assertIn('1 existing oversized', self.run_cap().stdout)
        self.run_cap('--strict', expected=1)
        self.write(LEGACY, 617)
        self.run_cap(expected=1)
        self.write(LEGACY, 300)
        self.assertNotIn('oversized', self.run_cap('--strict').stdout)

    def test_generated_fixtures_and_symlinks_are_excluded(self):
        self.write('apps/player/testdata/fixture.js', 301)
        self.write('docs/example.py', 301)
        generated = self.write('packages/sample/generated.go', 301)
        generated.write_text('// Code generated by fixture. DO NOT EDIT.\n' + generated.read_text())
        (self.repo / 'external.swift').symlink_to(self.repo / 'docs/example.py')
        self.run_cap()
        self.git('add', '.')
        self.run_cap('--staged')
        self.git('commit', '-qm', 'fixture')
        self.run_cap('--head')

    def test_staged_snapshot_cannot_be_hidden_by_working_copy(self):
        name = 'packages/example.go'
        self.write(name, 301)
        self.git('add', '.')
        self.write(name, 10)
        self.run_cap()
        self.run_cap('--staged', expected=1)
        self.git('add', name)
        self.write(name, 301)
        self.run_cap('--staged')
        self.run_cap(expected=1)

    def test_head_snapshot_cannot_be_hidden_by_working_copy(self):
        name = 'packages/example.go'
        self.write(name, 301)
        self.git('add', '.')
        self.git('commit', '-qm', 'fixture')
        self.write(name, 10)
        self.run_cap('--head', expected=1)
        self.git('add', name)
        self.git('commit', '-qm', 'fix fixture')
        self.write(name, 301)
        self.run_cap('--head')

    def test_go_scope_compatibility_and_custom_limit(self):
        self.write('apps/player/example.go', 301)
        self.write('packages/example.swift', 301)
        self.write('packages/example.go', 300)
        self.run_cap('--go-only', '--scope', 'packages')
        self.run_cap('--go-only', '--scope', 'packages', '--limit', '299', expected=1)
        self.run_cap('--scope', 'packages', expected=1)

    def test_invalid_arguments_have_no_side_effects(self):
        cases = [('--scope', value) for value in ('', 'unknown', 'apps/../player')]
        cases += [('--limit', value) for value in ('', '0', '-1', '10000', 'many', '0300', '300 ')]
        cases += [('--unknown',), ('--scope',), ('--limit',), ('--staged', '--head')]
        cases += [('--revision', value) for value in ('', 'HEAD', '--all', 'a' * 1000)]
        cases += [('--revision', 'f' * 40)]
        for args in cases:
            with self.subTest(args=args):
                self.run_cap(*args, expected=2)

    def test_hooks_enforce_cap_while_other_gates_are_paused(self):
        for hook in ('pre-commit.sh', 'pre-push-main.sh'):
            with self.subTest(hook=hook):
                name = 'packages/example.go'
                self.write(name, 301)
                self.git('add', '.')
                self.git('commit', '--allow-empty', '-qm', 'fixture')
                command = ['bash', str(ROOT / 'scripts/tooling' / hook)]
                payload = f'refs/heads/main {self.git("rev-parse", "HEAD").decode().strip()} refs/heads/main {"0" * 40}\n'
                result = subprocess.run(command, cwd=self.repo, input=payload, text=True,
                                        capture_output=True)
                self.assertEqual(result.returncode, 1, result.stderr)
                self.assertIn(name, result.stderr)
                self.write(name, 300)
                self.git('add', name)
                self.git('commit', '-qm', 'fix fixture')
                payload = f'refs/heads/main {self.git("rev-parse", "HEAD").decode().strip()} refs/heads/main {"0" * 40}\n'
                result = subprocess.run(command, cwd=self.repo, input=payload, text=True,
                                        capture_output=True)
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn('paused', result.stdout)

    def test_push_checks_published_commit_instead_of_current_head(self):
        self.write('packages/example.go', 301)
        self.git('add', '.')
        self.git('commit', '-qm', 'oversized')
        oversized = self.git('rev-parse', 'HEAD').decode().strip()
        self.write('packages/example.go', 300)
        self.git('add', '.')
        self.git('commit', '-qm', 'corrected')
        self.run_cap('--head')
        payload = f'refs/heads/old {oversized} refs/heads/main {"0" * 40}\n'
        result = subprocess.run(['bash', str(ROOT / 'scripts/tooling/pre-push-main.sh')],
                                cwd=self.repo, input=payload, text=True, capture_output=True)
        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertIn('packages/example.go', result.stderr)


if __name__ == '__main__':
    unittest.main()
