import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { expect, test } from "@playwright/test";

const manifestPath = process.env.KINOSAIL_SUBTITLE_ACTION_NATIVE_MANIFEST;
const width = Number(process.env.KINOSAIL_SUBTITLE_ACTION_NATIVE_WIDTH ?? "390");
test.skip(!manifestPath, "requires a fresh one-mutation native-fixture ready.json");

test(`actual completed subtitle mutation with lost response recovers at ${width}px`, async ({ page }, testInfo) => {
  const manifest = JSON.parse(await readFile(manifestPath!, "utf8"));
  expect([390, 1440]).toContain(width);
  expect(["save", "restore"]).toContain(manifest.action);
  const root = dirname(manifestPath!), sidecar = join(root, "media", "R06 Example.en.srt");
  const before = await readFile(sidecar);
  expect(hash(before)).toBe(manifest.beforeCurrentSHA256);
  expect(hash(await readFile(join(root, "media", "R06 Example.mp4")))).toBe(manifest.clipSHA256);
  const excludedAction = manifest.action === "save" ? "restore" : "apply";
  const guard = await page.request.post(`${manifest.url}/api/v1/subtitle-library/${manifest.id}/${excludedAction}`, { data: "invalid-json", headers: { "Content-Type": "application/json" } });
  expect(guard.status()).toBe(405);
  expect(await guard.text()).toContain("one selected mutation only");
  const requests: Array<{ method: string; path: string }> = [], media: Array<{ status: number; contentRange?: string }> = [];
  page.on("request", request => requests.push({ method: request.method(), path: new URL(request.url()).pathname }));
  page.on("response", response => { if (new URL(response.url()).pathname.startsWith("/media/")) media.push({ status: response.status(), contentRange: response.headers()["content-range"] }); });
  await testInfo.attach("native-verification-context", { contentType: "application/json", body: JSON.stringify({ ...manifest, width, browser: testInfo.project.name, browserVersion: page.context().browser()?.version(), command: "playwright test subtitle-action-recovery-native.spec.ts --workers=1", routing: "no Playwright route interception; actual public Go preparation, activation and status; selected disposable mutation completion is observed before the fixture withholds only its activation acknowledgment; browser elapsed time controlled" }) });
  await page.setViewportSize({ width, height: 900 });
  await page.clock.install();
  await page.goto(`${manifest.url}/subtitles/inspect/${manifest.id}?language=en`);
  const language = page.locator('#subtitle-edit-form [name="language"]'), video = page.locator("video");
  await expect(language).toBeEnabled();
  await expect.poll(() => video.evaluate(video => video.readyState)).toBeGreaterThanOrEqual(2);
  expect(await video.evaluate(video => video.duration)).toBe(12);
  await video.evaluate(video => { video.muted = true; return video.play(); });
  await expect.poll(() => video.evaluate(video => video.getVideoPlaybackQuality().totalVideoFrames)).toBeGreaterThan(0);
  await video.evaluate(video => video.pause());
  if (manifest.action === "save") {
    await page.getByText("Timing anchors and cleanup", { exact: true }).click();
    await page.locator('[name="offset"]').fill("0.5");
    await page.getByRole("button", { name: "Preview changes", exact: true }).click();
    await expect(page.locator("#apply-subtitle")).toBeEnabled();
    await page.locator("#apply-subtitle").click();
  } else await page.locator("#restore-subtitle").click();
  await expect(language).toBeDisabled();
  await expect.poll(async () => (await (await page.request.get(`${manifest.url}/__fixture__/outcome`)).json()).completed).toBe(true);
  const outcome = await (await page.request.get(`${manifest.url}/__fixture__/outcome`)).json();
  expect(outcome.count).toBe(1);
  expect(outcome.preparations).toBe(1);
  expect(outcome.activationStatus).toBe(202);
  expect(outcome.operationID).toMatch(/^[a-f0-9]{64}$/);
  expect(outcome.status).toBe(manifest.action === "save" ? 200 : 204);
  expect(outcome.responseWithheld).toBe(true);
  expect(outcome.currentSHA256).not.toBe(manifest.beforeCurrentSHA256);
  expect(hash(await readFile(sidecar))).toBe(outcome.currentSHA256);
  expect(hash(await readFile(sidecar + ".kinosail.bak"))).toBe(manifest.beforeCurrentSHA256);
  if (manifest.action === "restore") expect(outcome.currentSHA256).toBe(manifest.initialSubtitleSHA256);
  await page.clock.fastForward(45_000);
  await expect(language, "a real completed write with a lost response must release safe editing").toBeEnabled({ timeout: 1500 });
  await expect(page.locator("#inspector-status")).toContainText(manifest.action === "save" ? /saved|completed|installed/i : /restored|completed/i);
  await expect(page.locator("#apply-subtitle")).toBeDisabled();
  const inspection = await (await page.request.get(`${manifest.url}/api/v1/subtitle-library/${manifest.id}/inspect?language=en`)).json();
  expect(inspection.fingerprint).toBe(outcome.currentSHA256);
  expect(inspection.current.cues.map((cue: { start: number; end: number; text: string }) => [cue.start, cue.end, cue.text])).toEqual(manifest.action === "save" ? [[1.5, 2.5, "First dialogue"], [4.5, 5.5, "Later dialogue"]] : [[1, 2, "First dialogue"], [4, 5, "Later dialogue"]]);
  const history = await (await page.request.get(`${manifest.url}/api/v1/subtitle-library?view=history`)).json();
  expect(history.matched).toBe(manifest.action === "save" ? 1 : 2);
  expect(history.history[0].action).toBe(manifest.action === "save" ? "updated" : "restored");
  const statusResponse = await page.request.get(`${manifest.url}/api/v1/subtitle-operations/${outcome.operationID}`);
  expect(statusResponse.status()).toBe(200);
  expect(statusResponse.headers()["cache-control"]).toBe("private, no-store");
  const receipt = await statusResponse.json();
  expect(receipt).toMatchObject({ id: outcome.operationID, state: "completed", outcome: "success", status: outcome.status });
  const cueTime = manifest.action === "save" ? "0:04.500 to 0:05.500" : "0:04.000 to 0:05.000";
  await page.getByRole("button", { name: `Seek Current cue 2: ${cueTime}`, exact: true }).click();
  await expect.poll(() => video.evaluate(video => video.currentTime)).toBe(manifest.action === "save" ? 3.5 : 3);
  expect(await video.evaluate(video => Array.from(video.textTracks).find(track => track.label === "Current")?.mode)).toBe("showing");
  expect(await video.evaluate(video => Array.from(video.textTracks).find(track => track.label === "Current")?.cues?.length)).toBe(2);
  await page.clock.fastForward(60_000);
  const final = await (await page.request.get(`${manifest.url}/__fixture__/outcome`)).json();
  expect(final.count).toBe(1);
  expect(final.preparations).toBe(1);
  expect(hash(await readFile(sidecar))).toBe(outcome.currentSHA256);
  expect(hash(await readFile(sidecar + ".kinosail.bak"))).toBe(outcome.recoverySHA256);
  expect(media.some(response => response.status === 206 && response.contentRange?.endsWith("/396548"))).toBe(true);
  const mutationPath = `/api/v1/subtitle-library/${manifest.id}/${manifest.action === "save" ? "apply" : "restore"}`;
  expect(requests.filter(request => request.method === "POST" && !request.path.endsWith("/preview"))).toEqual([{ method: "POST", path: "/api/v1/subtitle-operations" }, { method: "POST", path: mutationPath }]);
  expect(requests.some(request => request.method === "GET" && request.path === `/api/v1/subtitle-operations/${outcome.operationID}`)).toBe(true);
  await testInfo.attach("native-transport-and-integrity", { contentType: "application/json", body: JSON.stringify({ outcome, receipt, final, requests, media, rejectedOtherMutationStatus: guard.status(), historyActions: history.history.map((item: { action: string }) => item.action), publicFingerprint: inspection.fingerprint, currentAndRecoveryUnchangedAfterReconciliation: true, actualCurrentCueSeek: manifest.action === "save" ? 3.5 : 3 }) });
  await page.screenshot({ path: testInfo.outputPath(`${manifest.action}-native-reconciled-${width}.png`), fullPage: true });
});

function hash(data: Buffer) { return createHash("sha256").update(data).digest("hex"); }
