// ISO 639 language names are bundled for offline use.
export const mediaLanguages: readonly (readonly [string, string, string])[] = [
  ['aa', 'Afar', 'aar'],
  ['ab', 'Abkhazian', 'abk'],
  ['ae', 'Avestan', 'ave'],
  ['af', 'Afrikaans', 'afr'],
  ['ak', 'Akan', 'aka'],
  ['am', 'Amharic', 'amh'],
  ['an', 'Aragonese', 'arg'],
  ['ar', 'Arabic', 'ara'],
  ['as', 'Assamese', 'asm'],
  ['av', 'Avaric', 'ava'],
  ['ay', 'Aymara', 'aym'],
  ['az', 'Azerbaijani', 'aze'],
  ['ba', 'Bashkir', 'bak'],
  ['be', 'Belarusian', 'bel'],
  ['bg', 'Bulgarian', 'bul'],
  ['bi', 'Bislama', 'bis'],
  ['bm', 'Bambara', 'bam'],
  ['bn', 'Bangla', 'ben'],
  ['bo', 'Tibetan', 'bod'],
  ['br', 'Breton', 'bre'],
  ['bs', 'Bosnian', 'bos'],
  ['ca', 'Catalan', 'cat'],
  ['ce', 'Chechen', 'che'],
  ['ch', 'Chamorro', 'cha'],
  ['co', 'Corsican', 'cos'],
  ['cr', 'Cree', 'cre'],
  ['cs', 'Czech', 'ces'],
  ['cu', 'Church Slavic', 'chu'],
  ['cv', 'Chuvash', 'chv'],
  ['cy', 'Welsh', 'cym'],
  ['da', 'Danish', 'dan'],
  ['de', 'German', 'deu'],
  ['dv', 'Divehi', 'div'],
  ['dz', 'Dzongkha', 'dzo'],
  ['ee', 'Ewe', 'ewe'],
  ['el', 'Greek', 'ell'],
  ['en', 'English', 'eng'],
  ['eo', 'Esperanto', 'epo'],
  ['es', 'Spanish', 'spa'],
  ['et', 'Estonian', 'est'],
  ['eu', 'Basque', 'eus'],
  ['fa', 'Persian', 'fas'],
  ['ff', 'Fulah', 'ful'],
  ['fi', 'Finnish', 'fin'],
  ['fj', 'Fijian', 'fij'],
  ['fo', 'Faroese', 'fao'],
  ['fr', 'French', 'fra'],
  ['fy', 'Western Frisian', 'fry'],
  ['ga', 'Irish', 'gle'],
  ['gd', 'Scottish Gaelic', 'gla'],
  ['gl', 'Galician', 'glg'],
  ['gn', 'Guarani', 'grn'],
  ['gu', 'Gujarati', 'guj'],
  ['gv', 'Manx', 'glv'],
  ['ha', 'Hausa', 'hau'],
  ['he', 'Hebrew', 'heb'],
  ['hi', 'Hindi', 'hin'],
  ['ho', 'Hiri Motu', 'hmo'],
  ['hr', 'Croatian', 'hrv'],
  ['ht', 'Haitian Creole', 'hat'],
  ['hu', 'Hungarian', 'hun'],
  ['hy', 'Armenian', 'hye'],
  ['hz', 'Herero', 'her'],
  ['ia', 'Interlingua', 'ina'],
  ['id', 'Indonesian', 'ind'],
  ['ie', 'Interlingue', 'ile'],
  ['ig', 'Igbo', 'ibo'],
  ['ii', 'Sichuan Yi', 'iii'],
  ['ik', 'Inupiaq', 'ipk'],
  ['io', 'Ido', 'ido'],
  ['is', 'Icelandic', 'isl'],
  ['it', 'Italian', 'ita'],
  ['iu', 'Inuktitut', 'iku'],
  ['ja', 'Japanese', 'jpn'],
  ['jv', 'Javanese', 'jav'],
  ['ka', 'Georgian', 'kat'],
  ['kg', 'Kongo', 'kon'],
  ['ki', 'Kikuyu', 'kik'],
  ['kj', 'Kuanyama', 'kua'],
  ['kk', 'Kazakh', 'kaz'],
  ['kl', 'Kalaallisut', 'kal'],
  ['km', 'Khmer', 'khm'],
  ['kn', 'Kannada', 'kan'],
  ['ko', 'Korean', 'kor'],
  ['kr', 'Kanuri', 'kau'],
  ['ks', 'Kashmiri', 'kas'],
  ['ku', 'Kurdish', 'kur'],
  ['kv', 'Komi', 'kom'],
  ['kw', 'Cornish', 'cor'],
  ['ky', 'Kyrgyz', 'kir'],
  ['la', 'Latin', 'lat'],
  ['lb', 'Luxembourgish', 'ltz'],
  ['lg', 'Ganda', 'lug'],
  ['li', 'Limburgish', 'lim'],
  ['ln', 'Lingala', 'lin'],
  ['lo', 'Lao', 'lao'],
  ['lt', 'Lithuanian', 'lit'],
  ['lu', 'Luba-Katanga', 'lub'],
  ['lv', 'Latvian', 'lav'],
  ['mg', 'Malagasy', 'mlg'],
  ['mh', 'Marshallese', 'mah'],
  ['mi', 'Maori', 'mri'],
  ['mk', 'Macedonian', 'mkd'],
  ['ml', 'Malayalam', 'mal'],
  ['mn', 'Mongolian', 'mon'],
  ['mr', 'Marathi', 'mar'],
  ['ms', 'Malay', 'msa'],
  ['mt', 'Maltese', 'mlt'],
  ['my', 'Burmese', 'mya'],
  ['na', 'Nauru', 'nau'],
  ['nb', 'Norwegian Bokmål', 'nob'],
  ['nd', 'North Ndebele', 'nde'],
  ['ne', 'Nepali', 'nep'],
  ['ng', 'Ndonga', 'ndo'],
  ['nl', 'Dutch', 'nld'],
  ['nn', 'Norwegian Nynorsk', 'nno'],
  ['no', 'Norwegian', 'nor'],
  ['nr', 'South Ndebele', 'nbl'],
  ['nv', 'Navajo', 'nav'],
  ['ny', 'Nyanja', 'nya'],
  ['oc', 'Occitan', 'oci'],
  ['oj', 'Ojibwa', 'oji'],
  ['om', 'Oromo', 'orm'],
  ['or', 'Odia', 'ori'],
  ['os', 'Ossetic', 'oss'],
  ['pa', 'Punjabi', 'pan'],
  ['pi', 'Pali', 'pli'],
  ['pl', 'Polish', 'pol'],
  ['ps', 'Pashto', 'pus'],
  ['pt', 'Portuguese', 'por'],
  ['qu', 'Quechua', 'que'],
  ['rm', 'Romansh', 'roh'],
  ['rn', 'Rundi', 'run'],
  ['ro', 'Romanian', 'ron'],
  ['ru', 'Russian', 'rus'],
  ['rw', 'Kinyarwanda', 'kin'],
  ['sa', 'Sanskrit', 'san'],
  ['sc', 'Sardinian', 'srd'],
  ['sd', 'Sindhi', 'snd'],
  ['se', 'Northern Sami', 'sme'],
  ['sg', 'Sango', 'sag'],
  ['si', 'Sinhala', 'sin'],
  ['sk', 'Slovak', 'slk'],
  ['sl', 'Slovenian', 'slv'],
  ['sm', 'Samoan', 'smo'],
  ['sn', 'Shona', 'sna'],
  ['so', 'Somali', 'som'],
  ['sq', 'Albanian', 'sqi'],
  ['sr', 'Serbian', 'srp'],
  ['ss', 'Swati', 'ssw'],
  ['st', 'Southern Sotho', 'sot'],
  ['su', 'Sundanese', 'sun'],
  ['sv', 'Swedish', 'swe'],
  ['sw', 'Swahili', 'swa'],
  ['ta', 'Tamil', 'tam'],
  ['te', 'Telugu', 'tel'],
  ['tg', 'Tajik', 'tgk'],
  ['th', 'Thai', 'tha'],
  ['ti', 'Tigrinya', 'tir'],
  ['tk', 'Turkmen', 'tuk'],
  ['fil', 'Filipino', 'fil'],
  ['tn', 'Tswana', 'tsn'],
  ['to', 'Tongan', 'ton'],
  ['tr', 'Turkish', 'tur'],
  ['ts', 'Tsonga', 'tso'],
  ['tt', 'Tatar', 'tat'],
  ['tw', 'Twi', 'twi'],
  ['ty', 'Tahitian', 'tah'],
  ['ug', 'Uyghur', 'uig'],
  ['uk', 'Ukrainian', 'ukr'],
  ['ur', 'Urdu', 'urd'],
  ['uz', 'Uzbek', 'uzb'],
  ['ve', 'Venda', 'ven'],
  ['vi', 'Vietnamese', 'vie'],
  ['vo', 'Volapük', 'vol'],
  ['wa', 'Walloon', 'wln'],
  ['wo', 'Wolof', 'wol'],
  ['xh', 'Xhosa', 'xho'],
  ['yi', 'Yiddish', 'yid'],
  ['yo', 'Yoruba', 'yor'],
  ['za', 'Zhuang', 'zha'],
  ['zh', 'Chinese', 'zho'],
  ['zu', 'Zulu', 'zul'],
  ['yue', 'Cantonese', 'yue'],
  ['ckb', 'Central Kurdish', 'ckb'],
];

const aliases = new Map(
  mediaLanguages
    .filter(([tag]) => !tag.includes('-'))
    .map(([tag, , iso3]) => [iso3, tag]),
);
for (const [alias, tag] of Object.entries({
  alb: 'sq',
  arm: 'hy',
  baq: 'eu',
  bur: 'my',
  chi: 'zh',
  cze: 'cs',
  dut: 'nl',
  fre: 'fr',
  geo: 'ka',
  ger: 'de',
  gre: 'el',
  ice: 'is',
  mac: 'mk',
  mao: 'mi',
  may: 'ms',
  per: 'fa',
  rum: 'ro',
  slo: 'sk',
  tib: 'bo',
  wel: 'cy',
}))
  aliases.set(alias, tag);
export function playbackLanguageBase(value: string) {
  const base = value.toLowerCase().split('-')[0];
  return aliases.get(base) ?? base;
}
