package server

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"github.com/MikeO7/kinosail/packages/library"
	"github.com/MikeO7/kinosail/packages/transcodehardware"
	"github.com/MikeO7/kinosail/packages/workload"
)

func (manager *hlsManager) encodePresentation(ctx context.Context, item library.Item, root string, options transcodeSettings, recipe hlsRecipe, qualities []PlaybackQuality, audioBitrate int64, start float64) error { //nolint:cyclop,funlen // One decode feeds the complete switchable presentation.
	device := transcodehardware.DeviceKey(options)
	release, err := manager.workloads.AcquireEncoding(ctx, workload.Playback, len(qualities), device)
	if err != nil {
		return err
	}
	defer release()
	input, _ := videoArguments(options, strconv.Itoa(qualities[len(qualities)-1].Width))
	arguments := append([]string{"-hide_banner", "-loglevel", "error", "-filter_threads", "1", "-filter_complex_threads", "1", "-y"}, input...)
	if start > 0 {
		arguments = append(arguments, "-ss", ffmpegSeconds(start))
	}
	arguments = append(arguments, "-i", item.Path)
	encoderThreads := max(1, runtime.GOMAXPROCS(0)/len(qualities))
	for index, quality := range qualities {
		directory := filepath.Join(root, quality.Label)
		//nolint:gosec // G703: root is the validated cache path and the quality name is generated by Kinosail.
		if err := os.MkdirAll(directory, 0o700); err != nil {
			return err
		}
		_, video := videoArguments(options, strconv.Itoa(quality.Width))
		mapping, encoded := applyBurnIn(video, item.Path, recipe)
		label := "[v" + strconv.Itoa(index) + "]"
		for argument := range mapping {
			mapping[argument] = strings.ReplaceAll(mapping[argument], "[v]", label)
		}
		arguments = append(arguments, mapping...)
		if audioBitrate > 0 {
			arguments = append(arguments, "-map", "0:a:"+strconv.Itoa(recipe.audio)+"?")
			arguments = append(arguments, automaticSkipAudioArguments(recipe)...)
		}
		arguments = append(arguments, "-sn")
		arguments = append(arguments, encoded...)
		arguments = append(arguments, "-threads:v", strconv.Itoa(encoderThreads))
		videoRate := strconv.FormatInt(max(1, (quality.Bitrate-audioBitrate)/1000), 10) + "k"
		arguments = append(arguments, videoCompatibilityArguments(options.Codec)...)
		arguments = append(arguments, "-maxrate", videoRate, "-bufsize", videoRate)
		if audioBitrate > 0 {
			arguments = append(arguments, "-c:a", "aac", "-ac", "2", "-b:a", strconv.FormatInt(audioBitrate/1000, 10)+"k")
		}
		arguments = append(arguments, "-flags", "+cgop", "-force_key_frames", "expr:gte(t,n_forced*2)")
		arguments = append(arguments, hlsSegmentArguments("transcode", directory, filepath.Join(directory, "index.m3u8"))...)
	}
	//nolint:gosec // G204: executable is installation config and input is found only by a Library scan.
	if err := runHLSCommand(exec.CommandContext(ctx, manager.ffmpeg, arguments...), item.Path, root); err != nil {
		return err
	}
	for _, quality := range qualities {
		if err := finalizePlaylist(filepath.Join(root, quality.Label, "index.m3u8")); err != nil {
			return err
		}
	}
	return nil
}

func hlsSegmentArguments(mode, directory, playlist string) []string {
	flags := "temp_file+independent_segments"
	if mode == "remux" || mode == "audio-transcode" {
		flags = "temp_file+split_by_time"
	}
	return []string{"-f", "hls", "-hls_time", "4", "-hls_playlist_type", "event", "-hls_segment_type", "fmp4", "-hls_flags", flags, "-hls_fmp4_init_filename", "init.mp4", "-hls_segment_filename", filepath.Join(directory, "segment-%05d.m4s"), playlist}
}
