import { Platform, StyleSheet } from 'react-native';

import { spacing } from '@/design/tokens';

export const homeViewStyles = StyleSheet.create({
  screen: { flex: 1 },
  backdrop: {
    height: '70%',
    opacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
  },
  safeArea: { flex: 1 },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 76,
    paddingVertical: spacing.one,
  },
  headerAccessible: { alignItems: 'flex-start', flexDirection: 'column' },
  account: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.one,
    flexShrink: 1,
  },
  accountAccessible: { alignItems: 'flex-start', flexWrap: 'wrap' },
  server: { fontSize: 12, fontWeight: '700' },
  viewer: { fontSize: Platform.isTV ? 24 : 13, fontWeight: '600' },
  signOut: { minHeight: Platform.isTV ? 64 : 44, paddingHorizontal: spacing.two },
  theme: { minHeight: Platform.isTV ? 64 : 44, paddingHorizontal: spacing.two },
  content: { gap: spacing.six, paddingBottom: spacing.eight },
  contentCompact: { gap: spacing.three },
  quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.one },
  quickAction: {
    borderRadius: 24,
    paddingHorizontal: spacing.two,
    minHeight: Platform.isTV ? 64 : 44,
  },
  accountButton: {
    borderRadius: 24,
    minHeight: 44,
    paddingHorizontal: spacing.two,
    maxWidth: 240,
    flexShrink: 1,
  },
  heroCompact: {
    minHeight: 470,
    paddingTop: 220,
    paddingBottom: spacing.three,
    justifyContent: 'flex-end',
    gap: spacing.two,
  },
  heroTitleCompact: { fontSize: 42, lineHeight: 47, letterSpacing: -1.2 },
  heroSummaryCompact: { fontSize: 15, lineHeight: 22 },
  hero: {
    gap: spacing.two,
    maxWidth: 680,
    minHeight: Platform.isTV ? 330 : 260,
    paddingTop: Platform.isTV ? spacing.three : spacing.five,
  },
  eyebrow: {
    fontSize: Platform.isTV ? 18 : 11,
    fontWeight: '700',
    letterSpacing: 1.6,
  },
  heroTitle: {
    fontSize: Platform.isTV ? 72 : 42,
    fontWeight: '700',
    letterSpacing: -1.4,
    lineHeight: Platform.isTV ? 80 : 46,
  },
  heroSummary: {
    fontSize: Platform.isTV ? 28 : 16,
    lineHeight: Platform.isTV ? 36 : 24,
    maxWidth: 620,
  },
  heroAction: { alignSelf: 'flex-start', minWidth: 148 },
  empty: {
    gap: spacing.two,
    minHeight: 320,
    justifyContent: 'center',
    maxWidth: 660,
  },
  shelf: { gap: spacing.two },
  shelfTitle: {
    fontSize: Platform.isTV ? 32 : 21,
    fontWeight: '600',
    letterSpacing: -0.4,
  },
  shelfRow: { paddingBottom: Platform.isTV ? spacing.two : spacing.fine },
});
