package server

import "strings"

func tvPlayerTemplate(template string) string {
	template = strings.ReplaceAll(template, `data-title="{{.Title}}"`, `data-title="{{.Title}}" data-cast-api="/api/v1/items/{{.ID}}/cast"`)
	template = strings.Replace(template, `<button class="quiet" type="button" aria-label="Play on device" data-cast>{{icon "cast"}}</button>`, `<button class="quiet play-on-tv" type="button" data-tv-open aria-haspopup="dialog">{{icon "cast"}} Play on TV</button>`, 1)
	template = strings.Replace(template, `</audio>`, `</audio><button class="quiet play-on-tv" type="button" data-tv-open aria-haspopup="dialog">{{icon "cast"}} Play on TV</button>`, 1)
	return strings.Replace(template, `</main>`, `{{if ne .Kind "photo"}}`+tvPickerHTML+`{{end}}</main>`, 1)
}

const tvPickerHTML = `<dialog class="tv-picker" data-tv-picker aria-labelledby="tv-picker-title"><header><h2 id="tv-picker-title">Play on TV</h2><button class="quiet" type="button" data-tv-close>Close</button></header><p>Keep your TV and Kinosail Server on the same network.</p><section><h3>AirPlay / browser devices</h3><p>Apple TV and compatible smart TVs, or devices offered by your browser.</p><button hidden class="quiet" type="button" aria-label="Choose AirPlay or browser device" data-cast>Choose device</button><p data-tv-native-unavailable>Your browser does not offer a device picker. Try Google Cast or DLNA below.</p></section><section><h3>Google Cast / Chromecast</h3><p>Chromecast, Google TV, and TVs with Google Cast. Google’s connection tools load when you enable this option.</p><button class="quiet" type="button" data-tv-google>Enable Google Cast</button></section><section><h3>DLNA / UPnP TVs</h3><p>Search for compatible receivers on Kinosail Server’s network.</p><button class="quiet" type="button" data-tv-scan>Find DLNA TVs</button><div data-tv-devices></div></section><section><h3>Screen mirroring / Miracast</h3><p>For compatible Roku, Fire TV, and other TVs, enable mirroring on the TV, then use your device’s Screen Mirroring, Cast, or Smart View controls. Support depends on your phone, computer, and TV.</p></section><section hidden data-tv-controls><h3 data-tv-target></h3><output data-tv-position></output><div class="player-actions"><button class="quiet" type="button" data-tv-command="play">Play TV</button><button class="quiet" type="button" data-tv-command="pause">Pause TV</button><button class="quiet" type="button" data-tv-command="back">Back 10 seconds</button><button class="quiet" type="button" data-tv-command="forward">Forward 10 seconds</button><button class="quiet" type="button" data-tv-stop>Stop casting</button></div></section><p role="status" aria-live="polite" data-tv-status></p></dialog>`
