package server

import "strings"

func tvPlayerTemplate(template string) string {
	template = strings.ReplaceAll(template, `data-title="{{.Title}}"`, `data-title="{{.Title}}" data-cast-api="/api/v1/items/{{.ID}}/cast" data-cast-app-id="{{.CastAppID}}"`)
	template = strings.Replace(template, `<button class="quiet" type="button" aria-label="Play on device" data-cast>{{icon "cast"}}</button>`, `<button class="quiet play-on-tv" type="button" data-tv-open aria-haspopup="dialog">{{icon "cast"}} Play on another device</button>`, 1)
	template = strings.Replace(template, `</audio>`, `</audio><button class="quiet play-on-tv" type="button" data-tv-open aria-haspopup="dialog">{{icon "cast"}} Play on another device</button>`, 1)
	return strings.Replace(template, `</main>`, `{{if ne .Kind "photo"}}`+tvPickerHTML+`{{end}}</main>`, 1)
}

const tvPickerHTML = `<dialog class="tv-picker" data-tv-picker aria-labelledby="tv-picker-title"><header><h2 id="tv-picker-title">Play on another device</h2><button class="quiet" type="button" data-tv-close>Close</button></header><p>For Google Cast and DLNA, the receiver must be able to reach Kinosail Server.</p><section><h3>AirPlay / browser devices</h3><p>{{if or (eq .Kind "audio") (eq .Kind "audiobook")}}HomePod, AirPlay speakers and TVs, or devices offered by your browser.{{else}}Apple TV and AirPlay-enabled TVs, or devices offered by your browser.{{end}}</p><button hidden class="quiet" type="button" aria-label="Choose AirPlay or browser device" data-cast>Choose device</button><p data-tv-native-unavailable>Your browser does not offer a device picker. Try Google Cast or DLNA below.</p></section><section><h3>Google Cast / Chromecast</h3><p>{{if or (eq .Kind "audio") (eq .Kind "audiobook")}}Chromecast and Google TV{{if .CastAppID}}, plus compatible Cast speakers{{end}}.{{else}}Chromecast, Google TV and TVs with Google Cast.{{end}} Google’s connection tools load when you enable this option.{{if and (or (eq .Kind "audio") (eq .Kind "audiobook")) (not .CastAppID)}} Audio-only Cast speakers require a registered receiver app ID in Server configuration.{{end}}</p><button class="quiet" type="button" data-tv-google>Enable Google Cast</button></section><section><h3>DLNA / UPnP receivers</h3><p>{{if or (eq .Kind "audio") (eq .Kind "audiobook")}}Search for compatible speakers and TVs on Kinosail Server’s network.{{else}}Search for compatible TVs on Kinosail Server’s network.{{end}}</p><button class="quiet" type="button" data-tv-scan>Find DLNA receivers</button><div data-tv-devices></div></section><section><h3>Samsung and LG TVs</h3><p>Use AirPlay on models that offer it, Google Cast on models with Cast built in or a Chromecast, or DLNA when the TV offers a media renderer. Samsung Smart View and LG Screen Share mirror your phone or computer screen; they are not direct Cast receivers.</p></section>{{if eq .Kind "video"}}<section><h3>Screen mirroring / Miracast</h3><p>For compatible Roku, Fire TV, and other TVs, enable mirroring on the TV, then use your device’s Screen Mirroring, Cast, or Smart View controls. Support depends on your phone, computer, and TV.</p></section>{{end}}<section hidden data-tv-controls><h3 data-tv-target></h3><output data-tv-position></output><div class="player-actions"><button class="quiet" type="button" data-tv-command="play">Play</button><button class="quiet" type="button" data-tv-command="pause">Pause</button><button class="quiet" type="button" data-tv-command="back">Back 10 seconds</button><button class="quiet" type="button" data-tv-command="forward">Forward 10 seconds</button><button class="quiet" type="button" data-tv-stop>Stop casting</button></div></section><p role="status" aria-live="polite" data-tv-status></p></dialog>`
