package server

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"slices"
	"strings"

	"github.com/MikeO7/kinosail/packages/library"
)

func readBookmark(writer http.ResponseWriter, request *http.Request, index *libraryIndex, item library.Item) (mediaBookmark, bool) {
	// IDs are generated by the Server, never supplied by a client.
	var input struct {
		Title   string          `json:"title"`
		Seconds *float64        `json:"seconds"`
		Page    *int            `json:"page"`
		Offset  json.RawMessage `json:"offset"`
	}
	if !readMediaJSON(writer, request, &input) {
		return mediaBookmark{}, false
	}
	offset, err := parseReaderOffset(input.Offset)
	if err != nil {
		apiError(writer, err, http.StatusBadRequest)
		return mediaBookmark{}, false
	}
	value := mediaBookmark{ID: strings.Repeat("0", 64), Title: strings.TrimSpace(input.Title), Seconds: input.Seconds, Page: input.Page, Offset: offset}
	if err := value.validate(); err != nil || (item.Kind == "book") != (value.Page != nil) {
		apiError(writer, errors.New("invalid bookmark"), http.StatusBadRequest)
		return mediaBookmark{}, false
	}
	if !validBookmarkPage(writer, request, index, item.ID, value.Page) {
		return mediaBookmark{}, false
	}
	random := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, random); err != nil {
		apiError(writer, errMediaExperience, http.StatusInternalServerError)
		return mediaBookmark{}, false
	}
	value.ID = hex.EncodeToString(random)
	return value, true
}

func validBookmarkPage(writer http.ResponseWriter, request *http.Request, index *libraryIndex, itemID string, page *int) bool {
	if page == nil {
		return true
	}
	book, err := readerFor(request, index, itemID)
	if err != nil || *page > len(book.Pages) {
		apiError(writer, errors.New("invalid bookmark page"), http.StatusBadRequest)
		return false
	}
	return true
}

func bookmarkChange(method, key, bookmarkID string, value mediaBookmark, values []mediaBookmark) func(*mediaExperienceState) error {
	return func(next *mediaExperienceState) error {
		if method == http.MethodPost {
			if len(values) >= 100 {
				return errBookmarkLimit
			}
			values = append(values, value)
		} else if i := slices.IndexFunc(values, func(entry mediaBookmark) bool { return entry.ID == bookmarkID }); i >= 0 {
			values = append(values[:i], values[i+1:]...)
		}
		next.Bookmarks[key] = values
		return nil
	}
}

func bookmarkResponse(values []mediaBookmark, includeOffset bool) []mediaBookmark {
	if values == nil {
		values = []mediaBookmark{}
	}
	if !includeOffset {
		for i := range values {
			values[i].Offset = nil
		}
	}
	return values
}

func readBookmarkRequest(writer http.ResponseWriter, request *http.Request, index *libraryIndex, item library.Item) (mediaBookmark, bool) {
	if request.Method == http.MethodPost {
		return readBookmark(writer, request, index, item)
	}
	if request.Method == http.MethodDelete && !experienceKeyPattern.MatchString(request.PathValue("bookmark")) {
		apiError(writer, errors.New("invalid bookmark"), http.StatusBadRequest)
		return mediaBookmark{}, false
	}
	return mediaBookmark{}, true
}
