package server

import "strings"

func updateChoicePage(page string) string {
	page = enhanceTranscoderPage(page)
	page = strings.NewReplacer(
		`<label>Default playback <select name="mode"><option value="automatic" {{if eq .Playback "automatic"}}selected{{end}}>Automatic · Original first (Recommended)</option><option value="direct" {{if eq .Playback "direct"}}selected{{end}}>Original only</option><option value="compatible" {{if eq .Playback "compatible"}}selected{{end}}>Compatible version first</option></select></label>`, `<fieldset class="choice-set choice-cards"><legend>Default playback</legend><label class="choice-option"><input type="radio" name="mode" value="automatic" {{if eq .Playback "automatic"}}checked{{end}}><span><strong>Direct First (Recommended)</strong><small>Try the original first; switch only after a confirmed format failure.</small></span></label><label class="choice-option"><input type="radio" name="mode" value="direct" {{if eq .Playback "direct"}}checked{{end}}><span><strong>Direct Play only</strong><small>Never create a compatible stream.</small></span></label><label class="choice-option"><input type="radio" name="mode" value="compatible" {{if eq .Playback "compatible"}}checked{{end}}><span><strong>Compatibility first</strong><small>Use a compatible version, converting only what your device needs.</small></span></label></fieldset>`,
		`<label>{{t "Subtitles"}} <select name="subtitles"><option value="on" {{if ne .Subtitles "off"}}selected{{end}}>{{t "On"}}</option><option value="off" {{if eq .Subtitles "off"}}selected{{end}}>{{t "Off"}}</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>{{t "Subtitles"}}</legend><label class="choice-option"><input type="radio" name="subtitles" value="on" {{if ne .Subtitles "off"}}checked{{end}}><span>{{t "On"}}</span></label><label class="choice-option"><input type="radio" name="subtitles" value="off" {{if eq .Subtitles "off"}}checked{{end}}><span>{{t "Off"}}</span></label></fieldset>`,
		`<label>Conversion preference <select name="quality"><option value="automatic" {{if eq .Transcoder "automatic"}}selected{{end}}>Automatic ({{t "Recommended"}})</option><option value="speed" {{if eq .Transcoder "speed"}}selected{{end}}>Prefer speed</option><option value="quality" {{if eq .Transcoder "quality"}}selected{{end}}>Prefer quality</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>Conversion preference</legend><label class="choice-option"><input type="radio" name="quality" value="automatic" {{if eq .Transcoder "automatic"}}checked{{end}}><span>Automatic</span></label><label class="choice-option"><input type="radio" name="quality" value="speed" {{if eq .Transcoder "speed"}}checked{{end}}><span>Prefer speed</span></label><label class="choice-option"><input type="radio" name="quality" value="quality" {{if eq .Transcoder "quality"}}checked{{end}}><span>Prefer quality</span></label></fieldset>`,
		`<label>Theme <select aria-label="Theme" data-theme-choice><option value="dark">Dark (default)</option><option value="light">Light</option><option value="system">System</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>Theme</legend><label class="choice-option"><input type="radio" name="theme" value="dark" data-theme-choice checked><span>Dark</span></label><label class="choice-option"><input type="radio" name="theme" value="light" data-theme-choice><span>Light</span></label><label class="choice-option"><input type="radio" name="theme" value="system" data-theme-choice><span>System</span></label></fieldset>`,
		`<label>Profile type <select name="owner"><option value="false" {{if not .Owner}}selected{{end}}>Viewer</option><option value="true" {{if .Owner}}selected{{end}}>Owner</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>Profile type</legend><label class="choice-option"><input type="radio" name="owner" value="false" {{if not .Owner}}checked{{end}}><span>Viewer</span></label><label class="choice-option"><input type="radio" name="owner" value="true" {{if .Owner}}checked{{end}}><span>Owner</span></label></fieldset>`,
		`<label>Profile type <select name="owner"><option value="false">Viewer</option><option value="true">Owner</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>Profile type</legend><label class="choice-option"><input type="radio" name="owner" value="false" checked><span>Viewer</span></label><label class="choice-option"><input type="radio" name="owner" value="true"><span>Owner</span></label></fieldset>`,
		`<label>Content <select name="rating"><option value="family" {{if or (eq .Rating "") (eq .Rating "family")}}selected{{end}}>Through PG / TV-PG</option><option value="teen" {{if eq .Rating "teen"}}selected{{end}}>Through PG-13 / TV-14</option><option value="all" {{if eq .Rating "all"}}selected{{end}}>All ratings</option></select></label>`, `<fieldset class="choice-set choice-cards"><legend>Content</legend><label class="choice-option"><input type="radio" name="rating" value="family" {{if or (eq .Rating "") (eq .Rating "family")}}checked{{end}}><span>Through PG / TV-PG</span></label><label class="choice-option"><input type="radio" name="rating" value="teen" {{if eq .Rating "teen"}}checked{{end}}><span>Through PG-13 / TV-14</span></label><label class="choice-option"><input type="radio" name="rating" value="all" {{if eq .Rating "all"}}checked{{end}}><span>All ratings</span></label></fieldset>`,
		`<label>Content <select name="rating"><option value="family">Through PG / TV-PG</option><option value="teen">Through PG-13 / TV-14</option><option value="all">All ratings</option></select></label>`, `<fieldset class="choice-set choice-cards"><legend>Content</legend><label class="choice-option"><input type="radio" name="rating" value="family" checked><span>Through PG / TV-PG</span></label><label class="choice-option"><input type="radio" name="rating" value="teen"><span>Through PG-13 / TV-14</span></label><label class="choice-option"><input type="radio" name="rating" value="all"><span>All ratings</span></label></fieldset>`,
		`<label>Content access<select name="rating"><option value="family">Through PG / TV-PG</option><option value="teen">Through PG-13 / TV-14</option><option value="all">All ratings</option></select></label>`, `<fieldset class="choice-set choice-cards"><legend>Content access</legend><label class="choice-option"><input type="radio" name="rating" value="family" checked><span>Through PG / TV-PG</span></label><label class="choice-option"><input type="radio" name="rating" value="teen"><span>Through PG-13 / TV-14</span></label><label class="choice-option"><input type="radio" name="rating" value="all"><span>All ratings</span></label></fieldset>`,
		`<label>Source <select name="source"><option value="plex">Plex</option><option value="jellyfin">Jellyfin</option></select></label>`, `<fieldset class="choice-set segmented-choice"><legend>Source</legend><label class="choice-option"><input type="radio" name="source" value="plex" checked><span>Plex</span></label><label class="choice-option"><input type="radio" name="source" value="jellyfin"><span>Jellyfin</span></label></fieldset>`,
	).Replace(page)
	oldChoice := `<label>Update checks <select name="mode"><option value="manual" {{if not .Updates.Automatic}}selected{{end}}>Manual only</option><option value="automatic" {{if .Updates.Automatic}}selected{{end}}>Check about once a day</option></select></label>`
	newChoice := `<fieldset class="wizard-update"><legend>Update preference</legend><label class="wizard-check"><input type="radio" name="mode" value="manual" {{if not .Updates.Automatic}}checked{{end}}><span><strong>Choose when to update</strong><small>Approve each signed update from Settings.</small></span></label><label class="wizard-check"><input type="radio" name="mode" value="automatic" {{if .Updates.Automatic}}checked{{end}}><span><strong>Install updates automatically</strong><small>Back up first, wait for idle playback, verify the signed update, check health, and roll back on failure.</small></span></label></fieldset>`
	page = strings.ReplaceAll(page, oldChoice, newChoice)
	page = strings.ReplaceAll(page, `<strong class="status" role="status">{{.UpdateText}}</strong></p>`, `<strong class="status" role="status">{{.UpdateText}}</strong></p><p>{{.UpdateManagerText}}</p>`)
	page = strings.NewReplacer(`Check GitHub now`, `Check and update now`, `Check for updates`, `Check and update now`).Replace(page)
	page = strings.ReplaceAll(page, `Choose update checks`, `Choose how Kinosail updates`)
	page = strings.ReplaceAll(page, `The Owner notification only says that an update is available. Kinosail never installs updates or gains access to Docker.`, `The installed Docker or native update adapter performs the update. Kinosail does not gain direct access to Docker or system package tools.`)
	page = strings.ReplaceAll(page, `Kinosail only shows an Owner notification. Installation stays manual and uses the verified installer.`, `The installed Docker or native update adapter performs the update with the same safety checks.`)
	return strings.NewReplacer(`/static/theme.js?v=electric-1`, `/static/theme.js?v=electric-1`, `/static/app.css?v=electric-1`, `/static/app.css?v=electric-1`).Replace(page)
}
