package server

const supporterHTML = `{{- define "supporterBadge"}}<div class="supporter-badge{{if .Active}} is-active{{end}}{{if .Expired}} is-archived{{end}}" data-family="{{.Family}}" data-rank="{{.Rank}}" data-service-count="{{.ServiceCount}}" role="img" aria-label="Kinosail Player {{.FamilyName}}, level {{.Rank}}, {{.Name}}{{if .Expired}}, archived{{else if .Active}}, active{{end}}"><img class="supporter-badge-art" width="360" height="360" src="/static/supporter/badges/{{if eq .Family "masterwork"}}supporter-rank-{{.Rank}}{{else}}{{.Family}}-{{.Rank}}{{end}}.svg?v=4" alt="" decoding="async"></div>{{end}}
{{- define "supporterRecord"}}<p>{{if eq .Family "living-standard"}}{{if .Expired}}Archived after {{.Until}}{{else}}Active through {{.Until}}{{end}}{{else}}Permanent{{end}} · Since {{.Since}}{{if .Founding}} · Founding{{end}}</p>{{if .ServiceMarks}}<p class="service-record">Service marks: {{range $index, $mark := .ServiceMarks}}{{if $index}} · {{end}}{{$mark}} months{{end}}</p>{{end}}{{if .CompleteFleet}}<p class="fleet-honor">Complete Fleet · {{.FleetEdition}} · {{.FleetAppCount}} apps</p>{{end}}{{end}}
{{- define "supporterActions"}}<div class="supporter-certificate-actions"><a class="mode" href="{{.CertificateURL}}" download>Download {{.FamilyName}} certificate</a><button class="quiet" type="button" data-supporter-share="{{.Family}}" hidden>Share {{.FamilyName}}</button><output data-supporter-share-status="{{.Family}}" aria-live="polite"></output></div>{{end}}
{{- define "supporterOwned"}}<article class="owned-badge{{if .Expired}} is-archived{{end}}">{{template "supporterBadge" .}}<div><span class="badge-family">{{.FamilyName}} · Level {{.Rank}}</span><h3>{{.Name}}</h3>{{template "supporterRecord" .}}{{if .RecognitionName}}<p class="recognition-name">Issued to {{.RecognitionName}}</p>{{end}}{{template "supporterActions" .}}<details class="supporter-certificate-preview"><summary>Preview {{.FamilyName}} certificate</summary><img src="{{.CertificateURL}}" width="1200" height="630" loading="lazy" alt="Your Kinosail Player {{.FamilyName}} certificate"></details></div></article>{{end}}
{{- define "supporterGallery"}}<ol class="supporter-gallery">{{range .}}<li class="{{if eq .State "Your badge"}}current{{else if eq .State "Collected"}}collected{{else if eq .State "Archived"}}expired{{end}}">{{template "supporterBadge" .}}<div class="supporter-level-copy"><span class="badge-family">Level {{.Rank}}</span><h3>{{.Name}}</h3><p>{{.Detail}}</p>{{if ne .State "Available"}}<span class="tier-state">{{.State}}</span>{{end}}</div><p class="supporter-price" data-supporter-price="{{.Rank}}"></p></li>{{end}}</ol>{{end}}
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0d0b"><link rel="icon" href="/static/icon.svg?v=8"><title>Your honors · Kinosail Player</title><script src="/static/theme.js?v=electric-1"></script><link rel="stylesheet" href="/static/app.css?v=electric-1"><script defer src="/static/main.kinosail.bundle.js?v=12"></script><script defer src="/static/supporter.js?v=11"></script></head>
<body class="supporter-page"><a class="skip" href="#main">Skip to content</a><main id="main" class="supporter-shell">
<nav class="supporter-back" aria-label="Return to Kinosail"><a class="back" href="/">{{icon "back"}} Library</a><a href="/settings">Settings</a></nav>
<header class="supporter-intro"><span class="eyebrow">Kinosail Player</span><h1>A place in the story.</h1>{{if not .HasBadges}}<p>However you’re here, you’re welcome. Kinosail stays complete and free to use. Your support gives it room to grow.</p>{{end}}</header>
{{if .Error}}<p class="supporter-error" role="alert">{{.Error}}</p>{{end}}
{{with .Featured}}<section id="thank-you" class="supporter-honor" aria-labelledby="honor-title"><div class="supporter-honor-art">{{template "supporterBadge" .}}</div><div class="supporter-honor-copy"><span class="badge-family">{{.FamilyName}} · Level {{.Rank}}</span><h2 id="honor-title">{{.Name}}</h2><p class="supporter-thanks">Thank you{{if .RecognitionName}}, {{.RecognitionName}}{{end}}.</p><p>{{if .Expired}}Your support is part of Kinosail’s story. Your Living Standard stays in your archive, with our gratitude.{{else}}You help make a private cinema feel like home. We’re grateful you’ve chosen to be part of Kinosail’s story.{{end}}</p>{{template "supporterRecord" .}}<p class="supporter-signoff">With gratitude,<br><strong>Kinosail</strong></p><button class="quiet supporter-replay" type="button" data-supporter-replay hidden>Replay badge reveal</button></div></section>{{end}}
{{if .HasBadges}}<section class="supporter-owned" aria-labelledby="owned-title"><header><span class="eyebrow">Made possible by you</span><h2 id="owned-title">Your honors</h2><p>Your one-time badge is permanent. Recurring badges stay in your archive when support ends.</p></header><div class="supporter-owned-grid">{{with .Living}}{{template "supporterOwned" .}}{{end}}{{with .Patron}}{{template "supporterOwned" .}}{{end}}</div>
<form id="recognition" class="supporter-display" method="post" action="/supporter/display"><label for="supporter-display">Badge shown in navigation</label><select name="display" id="supporter-display"><option value="automatic" {{if or (eq .Display "automatic") (eq .Display "")}}selected{{end}}>Automatic</option>{{if .Living}}<option value="living-standard" {{if eq .Display "living-standard"}}selected{{end}}>Living Standard</option>{{end}}{{if .Patron}}<option value="patron-order" {{if eq .Display "patron-order"}}selected{{end}}>Patron Order</option>{{end}}<option value="hidden" {{if eq .Display "hidden"}}selected{{end}}>Hide in navigation</option></select><button>Save display choice</button><p class="muted">Automatic shows an active Living Standard first, then a Patron Order. Saved on this Server; hiding recognition keeps your honors and certificates.</p></form>
{{with .Masterwork}}<article class="supporter-masterwork{{if .Active}} is-active{{else}} is-dormant{{end}}">{{template "supporterBadge" .}}<div><span class="badge-family">Player masterwork · Level {{.Rank}}</span><h3>{{.Title}}</h3><p>Full Sail joins your Patron Order and Living Standard. Its level rises when both families reach the next level.</p>{{if .Active}}<strong>Living aura active</strong>{{else}}<strong>Earned permanently · Living aura dormant</strong>{{end}}</div></article>{{end}}</section>
{{end}}
<section class="supporter-contribute" aria-labelledby="contribute-title"><span class="eyebrow">Entirely your choice</span><h2 id="contribute-title">Choose your support level.</h2><p>Each level has its own badge. Choose an amount that feels comfortable; every contribution is appreciated.</p><fieldset class="supporter-billing" hidden><legend>Contribution frequency</legend><label><input type="radio" name="billing" value="monthly" checked><span>Monthly</span></label><label><input type="radio" name="billing" value="annual"><span>Annual</span></label><label><input type="radio" name="billing" value="once"><span>One-time</span></label></fieldset>
<p data-supporter-billing-note aria-live="polite">Monthly support · Living Standard badge, active while your support is current.</p>
<div data-supporter-family="living-standard">{{template "supporterGallery" .LivingLevels}}</div><div data-supporter-family="patron-order" hidden>{{template "supporterGallery" .PatronLevels}}</div>
<p class="muted">Amounts in USD. Confirm available plans and final pricing on the support site.</p><a class="mode" href="{{.Status.SupportURL}}" rel="external noreferrer">Continue to support site</a><noscript><p>Open the support site for prices and all monthly, annual, and one-time levels.</p></noscript></section>
<details class="supporter-activation-disclosure"{{if .Error}} open{{end}}><summary>Already supported? Activate your badge</summary>
<section class="supporter-activation" aria-labelledby="activation-title"><div><span class="eyebrow">Already supporting?</span><h2 id="activation-title">Add or refresh one badge</h2><p>Paste your supporter key to add or refresh a badge. Your other badges stay yours. Kinosail does not store your key or payment details.</p></div><form method="post" action="/supporter/activate"><label>Supporter key<input name="key" required minlength="8" maxlength="128" pattern="[A-Za-z0-9_-]{8,128}" autocomplete="off" spellcheck="false"></label><label>Public certificate name <span>Optional. Sent only when you enter it. Available for levels 7–10.</span><input name="recognitionName" maxlength="80" autocomplete="off"></label><button>Activate badge</button></form></section>
</details>
<details class="supporter-privacy"><summary>About badges and privacy</summary><p>Monthly and annual support receive Living Standards, with service marks at 3, 6, 12, 24, 36, and 60 months. When support ends, the badge stays in your archive. One-time support receives permanent Patron Orders.</p><p>Activation sends your key, the Kinosail Player app ID, a random installation mark, and a public certificate name only if you enter one. No background checks. Certificates exclude keys, payment details, and private media.</p><p>One Complete Fleet key covers every included app. Each app keeps its own emblem and certificate. Living editions include future configured apps while active. Dated Patron editions stay fixed.</p></details>
<footer><p>However you’re here, you’re welcome.</p><a href="https://github.com/MikeO7/kinosail/blob/main/apps/player/SUPPORTERS.md" rel="external noreferrer">Public supporters</a></footer></main></body></html>`
