package playerweb

import "strings"

func PlayerTemplate(template string) string {
	template = strings.Replace(template, `data-room-disconnected="{{t "Room disconnected · reload to reconnect"}}"`, `data-room-disconnected="{{t "Room disconnected · reconnecting…"}}"`, 1)
	template = strings.ReplaceAll(template, `data-title="{{.Title}}"`, `data-title="{{.Title}}" data-artist="{{.Artist}}" data-album="{{.Album}}"`)
	template = strings.Replace(template, `{{else}}src="{{.Source}}{{if .Resume}}#t={{.Start}}{{end}}" {{if .AdaptiveSource}}`, `{{else}}{{if not .DeferDirect}}src="{{.Source}}{{if .Resume}}#t={{.Start}}{{end}}" {{end}}{{if .AdaptiveSource}}`, 1)
	template = strings.Replace(template, `data-playback-api="/api/v1/items/{{.ID}}/playback"`, `data-playback-api="/api/v1/items/{{.ID}}/playback" data-media-bitrate="{{.MediaBitrate}}" data-media-width="{{.MediaWidth}}" data-media-height="{{.MediaHeight}}" data-media-framerate="{{.MediaFrameRate}}"`, 1)
	template = strings.Replace(template, `<audio aria-label="{{.Title}}"`, `<audio aria-label="{{.Title}}" data-home-assistant="{{.HomeAssistant}}" data-playback-session="{{.PlaybackSession}}" data-playback-trace="/api/v1/items/{{.ID}}/playback-events"`, 1)
	template = strings.Replace(template, `<video aria-label="{{.Title}}"`, `<video aria-label="{{.Title}}" data-home-assistant="{{.HomeAssistant}}"`, 1)
	template = strings.Replace(template, `<video aria-label="{{.Title}}" data-home-assistant="{{.HomeAssistant}}"`, `<video aria-label="{{.Title}}" data-home-assistant="{{.HomeAssistant}}" data-playback-api="/api/v1/items/{{.ID}}/playback" data-playback-session="{{.PlaybackSession}}" data-playback-trace="/api/v1/items/{{.ID}}/playback-events"`, 1)
	template = strings.Replace(template, `data-auto-skip="{{.AutoSkip}}"`, `data-auto-skip="{{.AutoSkip}}" data-playback-policy="{{.PlaybackPolicy}}" data-playback-override="{{.PlaybackOverride}}" data-playback-label="{{.PlaybackLabel}}" data-playback-description="{{.PlaybackDescription}}" data-compatibility-mode="{{.CompatibilityMode}}" data-compatibility-label="{{.CompatibilityLabel}}" data-compatibility-description="{{.CompatibilityDescription}}" data-direct-url="?direct=1" data-compatible-url="?compatible=1"`, 1)
	template = strings.Replace(template, `<div class="player-stage-toolbar"><strong>{{.Title}}</strong>`, `<div class="player-stage-toolbar"><strong>{{.Title}}</strong><button class="player-mode-status" type="button" aria-label="{{"Playback method"}}: {{.PlaybackLabel}}" aria-live="polite" data-playback-mode-status>{{.PlaybackLabel}}</button><div class="player-stage-actions"><button class="quiet" type="button" aria-label="Play on device" data-cast>{{icon "cast"}}</button></div>`, 1)
	template = strings.Replace(template, `<header><strong>Playback settings</strong><button class="quiet" type="button" aria-label="Close playback settings" data-player-settings-close>Close</button></header>`, `<header><strong>{{"Playback settings"}}</strong><button class="quiet" type="button" aria-label="Close playback settings" data-player-settings-close>Close</button></header><details class="player-behavior"><summary>Playback behavior</summary><fieldset class="choice-set choice-cards player-policy" data-playback-mode><legend>{{"Playback policy"}}</legend><label class="choice-option"><input type="radio" name="playback-policy" value="direct-first" {{if eq .PlaybackPolicy "automatic"}}checked{{end}}><span><strong>{{"Direct First"}}</strong><small>Try the original file first. Use a compatible version if the format cannot play.</small></span></label><label class="choice-option"><input type="radio" name="playback-policy" value="direct-only" {{if eq .PlaybackPolicy "direct"}}checked{{end}}><span><strong>{{"Direct Play only"}}</strong><small>Use the original file and never convert it.</small></span></label><label class="choice-option"><input type="radio" name="playback-policy" value="compatible" {{if eq .PlaybackPolicy "compatible"}}checked{{end}} {{if not .CanTranscode}}disabled{{end}}><span><strong>{{t "Compatibility"}}</strong><small>Use a compatible version, converting only what your device needs.</small></span></label><small role="status" aria-live="polite" data-playback-reason>{{.PlaybackLabel}} · {{.PlaybackDescription}}</small></fieldset></details><div class="player-recovery" data-playback-recovery role="alert" hidden><strong>{{"Direct Play stopped"}}</strong><p data-playback-recovery-message></p><button type="button" data-player-fallback>Try again</button></div>`, 1)
	template = strings.Replace(template, `<span data-player-message>Loading video…</span>`, `<span data-player-message>Loading video…</span><button type="button" data-player-fallback hidden>Try again</button>`, 1)
	template = strings.Replace(template, `{{if .HLS}}Compatible version{{else}}Original file{{end}}</p></details>`, `<span data-playback-method-detail>{{.PlaybackLabel}}</span></p></details>`, 1)
	template = strings.Replace(template, `<button type="button" aria-label="Enter fullscreen" data-player-fullscreen>`, `<button hidden type="button" aria-label="Picture-in-Picture" aria-pressed="false" data-player-pip>{{icon "pip"}}</button><button type="button" aria-label="Enter fullscreen" data-player-fullscreen>`, 1)
	if start := strings.Index(template, `<details class="player-behavior">`); start >= 0 {
		end := start + strings.Index(template[start:], `</details>`) + len(`</details>`)
		behavior := template[start:end]
		template = template[:start] + template[end:]
		template = strings.Replace(template, `<p>Apple’s native controls`, behavior+`<p>Apple’s native controls`, 1)
	}
	return strings.Replace(template, `<button class="quiet" type="button" data-cast>Play on device</button>`, "", 1)
}
