package federation

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
)

type webProfile struct {
	ID       string
	OIDC     Identity
	SAML     Identity
	External string
	Managed  bool
	MFA      bool
}

type webEffects struct {
	errors, apiErrors, renders, signIns, audits int
	signInErr                                   error
}

func TestOIDCHTTPRoutesMFAAndProfileEffects(t *testing.T) { //nolint:funlen // One adapter contract exercises each route-side effect.
	t.Parallel()
	values := []webProfile{{ID: "viewer"}}
	profiles := webProfiles(&values)
	effects := &webEffects{}
	login := NewOIDCHTTP(OIDCConfig{}, profiles, webHooks(effects), func(writer http.ResponseWriter, _ *http.Request, challenge string) error {
		effects.renders++
		_, _ = writer.Write([]byte(challenge)) //nolint:gosec // Challenge is generated by the local test flow.
		return nil
	})
	if login.Configured() {
		t.Fatal("empty OIDC handler is configured")
	}
	mux := http.NewServeMux()
	login.Register(mux)
	assertHTTPStatus(t, mux, http.MethodGet, "/api/v1/session/oidc", "", http.StatusServiceUnavailable)
	assertHTTPStatus(t, mux, http.MethodGet, "/login/oidc/callback?code=x&state=y", "", http.StatusBadRequest)
	identity := Identity{Issuer: "issuer", Subject: "subject"}
	login.acceptCallback(httptest.NewRecorder(), httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil), OIDCCallback{ProfileID: "viewer", LinkSession: "session", Identity: identity})
	if values[0].OIDC != identity {
		t.Fatal("OIDC link callback did not persist identity")
	}
	login.SignInProfile(httptest.NewRecorder(), httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil), values[0])
	if effects.signIns != 1 || effects.audits != 1 {
		t.Fatalf("OIDC sign-in effects = %#v", effects)
	}
	values[0].MFA = true
	challenge, err := login.BeginMFA("viewer")
	if err != nil {
		t.Fatal(err)
	}
	assertHTTPStatus(t, mux, http.MethodGet, "/login/mfa?challenge="+challenge, "", http.StatusOK)
	assertHTTPStatus(t, mux, http.MethodPost, "/login/mfa", "challenge="+challenge+"&code=wrong", http.StatusUnauthorized)
	challenge, _ = login.BeginMFA("viewer")
	assertHTTPStatus(t, mux, http.MethodPost, "/login/mfa", "challenge="+challenge+"&code=valid", http.StatusSeeOther)
	if effects.renders != 1 || effects.signIns != 2 || effects.audits != 2 {
		t.Fatalf("OIDC MFA effects = %#v", effects)
	}
	assertHTTPStatus(t, mux, http.MethodDelete, "/api/v1/me/oidc", "", http.StatusNoContent)
	assertHTTPStatus(t, mux, http.MethodPost, "/account/oidc/unlink", "", http.StatusSeeOther)
}

func TestOIDCHTTPRejectsAndMapsFailures(t *testing.T) {
	t.Parallel()
	values := []webProfile{{ID: "viewer", MFA: true}}
	effects := &webEffects{signInErr: errors.New("session failed")}
	login := NewOIDCHTTP(OIDCConfig{}, webProfiles(&values), webHooks(effects), func(http.ResponseWriter, *http.Request, string) error { return nil })
	request := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil)
	for _, err := range []error{ErrInvalidCallback, ErrInvalidState, ErrAuthorizationDenied, ErrProviderUnavailable, ErrCodeExchange, ErrTokenInvalid} {
		login.writeCallbackError(httptest.NewRecorder(), request, err)
	}
	login.SignInProfile(httptest.NewRecorder(), request, values[0])
	values[0].MFA = false
	login.SignInProfile(httptest.NewRecorder(), request, values[0])
	login.acceptCallback(httptest.NewRecorder(), request, OIDCCallback{Identity: Identity{Issuer: "missing", Subject: "subject"}})
	if effects.errors < 8 || effects.signIns != 1 || effects.audits != 0 {
		t.Fatalf("OIDC rejected effects = %#v", effects)
	}
}

func TestSAMLHTTPRoutesProfilesAndFailures(t *testing.T) { //nolint:funlen // One adapter contract covers local SAML HTTP boundaries.
	t.Parallel()
	identity := Identity{Issuer: "issuer", Subject: "subject"}
	values := []webProfile{{ID: "viewer", SAML: identity}}
	effects := &webEffects{}
	hooks := webHooks(effects)
	login := NewSAMLHTTP(SAMLConfig{}, webProfiles(&values), hooks)
	if login.Configured() {
		t.Fatal("empty SAML handler is configured")
	}
	mux := http.NewServeMux()
	login.Register(mux)
	assertHTTPStatus(t, mux, http.MethodGet, "/api/v1/session/saml", "", http.StatusServiceUnavailable)
	assertHTTPStatus(t, mux, http.MethodPost, "/login/saml/acs", "bad", http.StatusBadRequest)
	login.signInIdentity(httptest.NewRecorder(), httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil), identity)
	if effects.signIns != 1 || effects.audits != 1 {
		t.Fatalf("SAML sign-in effects = %#v", effects)
	}
	values[0].MFA = true
	login.signInProfile(httptest.NewRecorder(), httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil), values[0])
	if effects.errors == 0 {
		t.Fatal("SAML MFA without challenge store was accepted")
	}
	for _, err := range []error{ErrInvalidCallback, ErrInvalidState, ErrProviderUnavailable, ErrNotConfigured, ErrTokenInvalid} {
		login.writeCallbackError(httptest.NewRecorder(), httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/", nil), err)
	}
	assertHTTPStatus(t, mux, http.MethodDelete, "/api/v1/me/saml", "", http.StatusNoContent)
	assertHTTPStatus(t, mux, http.MethodPost, "/account/saml/unlink", "", http.StatusSeeOther)
}

func webProfiles(values *[]webProfile) Profiles[webProfile] {
	var mutex sync.Mutex
	return Profiles[webProfile]{
		SessionActive: func(key, id string) bool { return key == "session" && id == "viewer" },
		Lock:          mutex.Lock, Unlock: mutex.Unlock,
		Clone:   func() []webProfile { return append([]webProfile(nil), (*values)...) },
		Persist: func([]webProfile) error { return nil },
		Commit:  func(updated []webProfile) { *values = updated },
		Inspect: func(profile webProfile) Profile {
			return Profile{ID: profile.ID, OIDC: profile.OIDC, SAML: profile.SAML, SCIMExternalID: profile.External, SCIMManaged: profile.Managed}
		},
		Apply: func(profile *webProfile, protocol Protocol, identity Identity) {
			if protocol == SAMLProtocol {
				profile.SAML = identity
			} else {
				profile.OIDC = identity
			}
		},
	}
}

func webHooks(effects *webEffects) WebHooks[webProfile] {
	return WebHooks[webProfile]{
		LinkSession:      func(*http.Request) string { return "session" },
		CurrentProfileID: func(*http.Request) string { return "viewer" }, SecureRequest: func(*http.Request) bool { return false },
		ProfileID: func(profile webProfile) string { return profile.ID }, RequiresMFA: func(profile webProfile) bool { return profile.MFA },
		VerifySecondFactor: func(_, code string) bool { return code == "valid" },
		SignIn:             func(http.ResponseWriter, *http.Request, string) error { effects.signIns++; return effects.signInErr },
		Audit:              func(*http.Request, webProfile) { effects.audits++ },
		Error: func(writer http.ResponseWriter, _ *http.Request, _ string, status int) {
			effects.errors++
			writer.WriteHeader(status)
		},
		APIError: func(writer http.ResponseWriter, _ error, status int) { effects.apiErrors++; writer.WriteHeader(status) },
	}
}

func assertHTTPStatus(t *testing.T, handler http.Handler, method, target, body string, want int) {
	t.Helper()
	request := httptest.NewRequestWithContext(t.Context(), method, target, strings.NewReader(body))
	if body != "" {
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	}
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	if response.Code != want {
		t.Fatalf("%s %s = %d want %d (%q)", method, target, response.Code, want, response.Body.String())
	}
}
