import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, lstatSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { readControl } from './control.mjs';
import { validateActiveOwned, validateOwned, validateReceipt } from './receipt.mjs';
const uuid='12345678-1234-1234-1234-123456789ABC';
function fixture(profile='tvos') {
 const project=mkdtempSync(join(tmpdir(),'kino-tv-admission-')); const root=join(project,'.e2e');mkdirSync(root,{mode:0o700}); const stat=lstatSync(root);
 const platform=profile==='tvos'?'ios':'android',device=platform==='ios'?uuid:'emulator-5554';
 const owned={run:'123-1',rootDev:stat.dev,rootIno:stat.ino,platform,profile,target:'tv',device,emulatorPID:platform==='ios'?null:123,emulatorStart:platform==='ios'?null:'12345',complete:false,...(platform==='ios'?{creationPending:{name:'Kinosail-TV-E2E-123-1',runtime:'com.apple.CoreSimulator.SimRuntime.tvOS-27-0',type:'com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-3rd-generation-4K',inventoryZero:true,inventorySHA256:'a'.repeat(64)}}:{})};
 const identity={platform,profile,target:'tv',device,port:'18769',revision:'b'.repeat(40),run:'123-1'};
 const appPath=resolve(project,'../..',platform==='ios'?'apps/player/apps/native/.build/tvos-simulator/Build/Products/Debug-appletvsimulator/KinosailPlayer.app':'apps/player/apps/android/app/build/outputs/apk/debug/app-debug.apk');
 const control={identity,appPath};
 function save(){writeFileSync(join(root,'owned-device.json'),JSON.stringify(owned),{mode:0o600});writeFileSync(join(root,'control.json'),JSON.stringify(control),{mode:0o600});}
 save();return{project,root,stat,owned,control,save,dispose:()=>rmSync(project,{recursive:true,force:true})};
}
test('both profiles admit exact private TV controls and owned virtual devices',()=>{for(const profile of ['tvos','androidtv']){const f=fixture(profile);try{assert.deepEqual(readControl(f.project),f.control);assert.equal(validateActiveOwned(f.owned,f.stat).target,'tv');}finally{f.dispose();}}});
test('unknown/missing/conflicting profile or target cannot admit controls',()=>{for(const mutate of [f=>delete f.control.identity.profile,f=>f.control.identity.profile='watchos',f=>f.control.identity.target='mobile',f=>f.control.identity.profile='androidtv',f=>f.control.identity.extra=true,f=>f.owned.profile='androidtv',f=>f.owned.target='mobile']){const f=fixture();try{mutate(f);f.save();assert.throws(()=>readControl(f.project));}finally{f.dispose();}}});
test('foreign phone binary, unowned device and duplicate JSON fields reject',()=>{for(const mode of ['phone','device','duplicate']){const f=fixture();try{if(mode==='phone')f.control.appPath=f.control.appPath.replace('tvos-simulator','ios-simulator').replace('appletvsimulator','iphonesimulator');if(mode==='device')f.owned.device='87654321-1234-1234-1234-123456789ABC';f.save();if(mode==='duplicate')writeFileSync(join(f.root,'control.json'),JSON.stringify(f.control).replace('"appPath":','"appPath":"foreign","appPath":'),{mode:0o600});assert.throws(()=>readControl(f.project));}finally{f.dispose();}}});
test('unresolved ownership cannot admit publication',()=>{const f=fixture();try{assert.throws(()=>validateOwned(f.owned,f.stat));f.owned.complete=true;assert.throws(()=>validateOwned(f.owned,f.stat));f.owned.creationPending=null;assert.equal(validateOwned(f.owned,f.stat).profile,'tvos');}finally{f.dispose();}});
test('TV receipt accepts only exact TV command templates and terminal journey facts',()=>{for(const profile of ['tvos','androidtv']){const f=fixture(profile);try{f.owned.complete=true;f.owned.creationPending=null;const receipt={revision:'b'.repeat(40),command:'python3 hosted.py '+profile,commands:[['go','build','-o',join(f.root,'bin/player'),'./apps/player/cmd/kinosail'],f.owned.platform==='ios'?['./scripts/build-apple.sh','tvos']:['avdmanager','create','avd','--name','Kinosail-TV-E2E-123-1','--package','system-images;android-36;android-tv;x86_64','--device','tv_1080p']],platform:f.owned.platform,profile,target:'tv',device:f.owned.device,environment:'disposable hosted simulator/emulator',data:'synthetic Example Movie (testsrc2/AAC); synthetic MFA Owner; actual dynamic pairing code',witness:{runtime:f.owned.platform==='ios'?'com.apple.CoreSimulator.SimRuntime.tvOS-27-0':'system-images;android-36;android-tv;x86_64'},result:1,cleanup:[],elapsedSeconds:3,packages:{e2e:'0.17.0','agent-device':'0.21.22'},boundaries:['no physical device','no phone/watchOS/Wear pairing','no casting/provider calls','no deployed server'],journey:{approval:'public Owner API and actual dynamic UI code',decodedFrames:true,partialProgressSeconds:2,watched:false,connectionRestored:true,progressPersisted:true,remoteFocus:true,menuReturned:true,tvForeground:true}};assert.equal(validateReceipt(receipt,f.owned,f.root).profile,profile);for(const change of [r=>r.target='mobile',r=>r.profile='wear',r=>r.commands.push(['./scripts/build-apple.sh','ios']),r=>r.journey.decodedFrames=false,r=>r.journey.menuReturned=false,r=>r.packages['@e2e-dev/mobile']='0.10.0']){const bad=structuredClone(receipt);change(bad);assert.throws(()=>validateReceipt(bad,f.owned,f.root));}}finally{f.dispose();}}});
